# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20180115_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuance',
            options={'verbose_name': 'Название книги', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='issuance',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Book', verbose_name='Название книги'),
        ),
    ]
