# Generated by Django 2.2.5 on 2020-01-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20180115_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuance',
            options={'verbose_name': 'Название книги', 'verbose_name_plural': 'Выдачи'},
        ),
    ]
