# Generated by Django 2.2.5 on 2020-01-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200112_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuance',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Выдачи'},
        ),
        migrations.AddField(
            model_name='issuance',
            name='review',
            field=models.CharField(default='null', max_length=255, verbose_name='Отзыв'),
        ),
    ]
